### ISSUE TITLE
;-; Are you ok?

### ISSUE THREAD

**Issue by EmotionalLove** [zeroeightysix/jtcui#3]
Sorry this isn't really the best way to contact you :/ I was just wondering what happened to you on Discord, you just kinda disappeared and it made me worry if you were okay...

**Comment by zeroeightysix** [comment]
I am okay. I've contacted you on discord, let's continue there, shall we?

**Comment by EmotionalLove** [comment]
I don't have that discord anymore, it's disabled, #9133 is my tag now.
